python3 train.py \
--project HiNAS-IR \
--name v5l_1280_FLIR \
--img_type ir \
--data data/data-ir.yaml \
--cfg models/yolov5l-ir.yaml \
--weights yolov5l.pt \
--device 0 \
--imgsz 1280 \
--epochs 100 \
--batch-size 5